### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by ORybka** [ORybka/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by OlhaRybchynska** [comment]
Hey there! I'm at the beginning of the Frontend developer's path. Currently, I learn actively Javascript and keen to learn some framework to broaden my opportunities. I started to work as a Frontend developer only 4 months ago so I dream about wide self-development engaging as many resources as possible.
