### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by ORybka** [ORybka/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by OlhaRybchynska** [comment]
olha.rybchynska@gmail.com
https://www.linkedin.com/in/olha-rybchynska/
https://github.com/ORybka
@orybka94
