### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by ORybka** [ORybka/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by OlhaRybchynska** [comment]
Frontend Developer
Bulls-media (Kyiv, Ukraine) (IT)
December 2020 — present
fix HTML and Wordpress websites;
build, test and and deploy internal company projects written with JavaScript

Project manager
Golden Staff Study (Kyiv, Ukraine) (Education)
September 2018 — April 2020
Launched 184 new projects in 62 companies in various fields in Ukraine;
92% of projects were launched within the prescribed deadline;
On average, held 2 meetings per week with new clients for further launch of projects;
Gave the presentations for the client's employees (for 5 to 35 people) before launch;
 
Economist
Medicina VM (Kyiv, Ukraine) (Medical and Healthcare)
September 2015 — July 2019
Сalculation of rates for medical services in different types of medical institutions, performance reporting;
Assistance in organizing workshops for up to 100 people;

Internship in the HR and Payroll Department
OTTO Work Force Poland (Wroclaw, Poland) (HR)
April 2018 — July 2018
Registration of external and internal correspondence, preparation of documents for dispatch, mail distribution and organization;
Support for employees within their work duties;

Internship in the Accounting Department
KOMSA Poland (Wroclaw, Poland) (Wholesale / Distribution / Import-export)
April 2017 — July 2017
Preparation of internal invoices, documents for VAT declarations;
Analysis of accounting data;
