### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by ORybka** [ORybka/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by OlhaRybchynska** [comment]
Technical skills:
semantic HTML layout;
CSS (SASS);
adaptive layout using media queries;
Bootstrap;
JavaScript;
jQuery;
CMS (Joomla);
building a project using webpack;
version control system GIT;
Figma.

Personal skills:
systematic approach to learning: during frontend self-learning;
thoroughness and attention to details: transferring only a completed project without shortcomings and errors (e.g. further successful support of my projects by colleagues);
teamwork: help colleagues to achieve the best result for the whole team. Transfer selected tasks without resistance when it's necessary;
multitasking: supported up to 15 clients simultaneously with different level of difficulty and from various areas;
completing urgent tasks in a short time;
initiative and proactivity: launched a new position after seeing its potential and economic benefit for the company;

Education
Wroclaw University of Economics
Wroclaw, Poland
Finance and Accounting 2018
Kyiv National Economic University named after Vadym Hetman
Finance and Credit   2015

Ecole de Commerce Europeenne - BBA INSEEC Bordeaux (France)
International Marketing
student exchange programme ERASMUS

Poznan University of Economics and Business (Poland)
Finance - student exchange programme

UDEMY: The Complete JavaScript Course 2020: Build Real Projects!
2020Edit
Basic course for learning such topics as JavaScript language basics, ES6+, DOM manipulations and events, OOP, Promises, Async/Await and AJAX, Webpack etc.
